version: "3.7"
services:
  admin_mysql:
    image: mysql:5.7
    build: './mysql/'
    command: --sql_mode=""
    container_name: admin_mysql
    environment:
      MYSQL_USER: juan
      MYSQL_PASSWORD: juan
      MYSQL_ROOT_PASSWORD: juan
    ports:
      - "33088:3306"
    restart: always
    networks:
      - p2l_backend
    volumes:
      - ./dbdata:/var/lib/mysql

  phpmyadmin:
    # Use phpmyadmin/phpmyadmin:5.0.2 image
    image: phpmyadmin/phpmyadmin
    # Connect to "my-network" network, as defined below
    networks:
      - p2l_backend
    # Map port 8080 on the host to port 80 inside the container
    # Syntax is: "HOST_PORT:CONTAINER_PORT"
    ports:
      - "5008:80"
    # Pass a list of environment variables to the container
    volumes:
      - /sessions
    environment:
      PMA_HOST: admin_mysql
    # Wait for "mysql" container to start first
    depends_on:
      - admin_mysql

  admin_apache:
    build: './apache/'
    container_name: admin_apache
    depends_on:
      - admin_mysql
    networks:
      - p2l_frotend
      - p2l_backend
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9001
    ports:
      - "8668:80"
    volumes:
      - "./html:/var/www/html"

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - "./html:/var/www/html"
volumes:
  mysql-data:

networks:
  p2l_frotend:
  p2l_backend: